-- AI ticket policies, versioned prompts and review drafts.
CREATE TABLE cc_ai_ticket_policy (
    id BIGINT NOT NULL,
    tenant_id VARCHAR(20) NOT NULL DEFAULT '000000',
    ai_agent_id BIGINT NOT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 0,
    creation_mode VARCHAR(32) NOT NULL DEFAULT 'DRAFT_REVIEW',
    ticket_template_id BIGINT NULL,
    trigger_types_json TEXT NULL,
    include_intents_json TEXT NULL,
    exclude_intents_json TEXT NULL,
    confidence_threshold DECIMAL(8,6) NOT NULL DEFAULT 0.800000,
    missing_required_action VARCHAR(32) NOT NULL DEFAULT 'KEEP_DRAFT',
    duplicate_policy VARCHAR(32) NOT NULL DEFAULT 'MERGE_PENDING',
    duplicate_window_hours INT NOT NULL DEFAULT 24,
    after_create_action VARCHAR(32) NOT NULL DEFAULT 'KEEP_PENDING',
    customer_template_id BIGINT NULL,
    default_skill_group_id BIGINT NULL,
    default_values_json TEXT NULL,
    active_prompt_version_id BIGINT NULL,
    version INT NOT NULL DEFAULT 0,
    create_dept BIGINT NULL,
    create_by BIGINT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT NULL,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_ticket_policy_agent (tenant_id, ai_agent_id),
    KEY idx_ai_ticket_policy_enabled (tenant_id, enabled)
) ENGINE=InnoDB COMMENT='AI automatic ticket policy';

CREATE TABLE cc_ai_ticket_prompt_version (
    id BIGINT NOT NULL,
    tenant_id VARCHAR(20) NOT NULL DEFAULT '000000',
    policy_id BIGINT NOT NULL,
    version_no INT NOT NULL,
    version_name VARCHAR(128) NULL,
    prompt_content LONGTEXT NOT NULL,
    protocol_version VARCHAR(32) NOT NULL,
    prompt_hash CHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    published_by BIGINT NULL,
    published_at DATETIME NULL,
    create_dept BIGINT NULL,
    create_by BIGINT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT NULL,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_ticket_prompt_version (tenant_id, policy_id, version_no),
    KEY idx_ai_ticket_prompt_status (tenant_id, policy_id, status)
) ENGINE=InnoDB COMMENT='AI ticket prompt versions';

CREATE TABLE cc_ai_ticket_draft (
    id BIGINT NOT NULL,
    tenant_id VARCHAR(20) NOT NULL DEFAULT '000000',
    policy_id BIGINT NOT NULL,
    ai_agent_id BIGINT NOT NULL,
    source_call_id VARCHAR(64) NOT NULL,
    customer_id BIGINT NULL,
    caller_number VARCHAR(32) NULL,
    ticket_template_id BIGINT NULL,
    prompt_version_id BIGINT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING_REVIEW',
    confidence DECIMAL(8,6) NULL,
    title VARCHAR(256) NULL,
    summary TEXT NULL,
    form_data_json LONGTEXT NULL,
    missing_fields_json TEXT NULL,
    evidence_json LONGTEXT NULL,
    failure_reason VARCHAR(1000) NULL,
    formal_ticket_id BIGINT NULL,
    reviewed_by BIGINT NULL,
    reviewed_at DATETIME NULL,
    version INT NOT NULL DEFAULT 0,
    create_dept BIGINT NULL,
    create_by BIGINT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT NULL,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_ticket_draft_call (tenant_id, policy_id, source_call_id, deleted),
    KEY idx_ai_ticket_draft_review (tenant_id, status, create_time),
    KEY idx_ai_ticket_draft_agent (tenant_id, ai_agent_id, create_time)
) ENGINE=InnoDB COMMENT='AI generated ticket drafts';

CREATE TABLE cc_ai_ticket_draft_audit (
    id BIGINT NOT NULL,
    tenant_id VARCHAR(20) NOT NULL DEFAULT '000000',
    draft_id BIGINT NOT NULL,
    action_type VARCHAR(32) NOT NULL,
    before_data_json LONGTEXT NULL,
    after_data_json LONGTEXT NULL,
    remark VARCHAR(500) NULL,
    create_dept BIGINT NULL,
    create_by BIGINT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT NULL,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_ai_ticket_draft_audit (tenant_id, draft_id, create_time)
) ENGINE=InnoDB COMMENT='AI ticket draft audit log';

ALTER TABLE cc_ticket
    ADD COLUMN source_type VARCHAR(32) NULL COMMENT 'Ticket source type' AFTER source_call_id,
    ADD COLUMN source_draft_id BIGINT NULL COMMENT 'AI ticket draft ID' AFTER source_type,
    ADD COLUMN ai_agent_id BIGINT NULL COMMENT 'AI agent ID' AFTER source_draft_id,
    ADD UNIQUE KEY uk_cc_ticket_source_draft (tenant_id, source_draft_id, deleted);
