CREATE TABLE cc_ai_ticket_draft_task (
    id BIGINT NOT NULL,
    tenant_id VARCHAR(20) NOT NULL DEFAULT '000000',
    policy_id BIGINT NOT NULL,
    ai_agent_id BIGINT NOT NULL,
    call_session_id BIGINT NULL,
    business_call_id VARCHAR(64) NOT NULL,
    trigger_type VARCHAR(32) NOT NULL DEFAULT 'CALL_ENDED',
    call_completed TINYINT(1) NOT NULL DEFAULT 0,
    transcript_ready TINYINT(1) NOT NULL DEFAULT 0,
    transcript_id BIGINT NULL,
    prompt_version_id BIGINT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'WAITING',
    retry_count INT NOT NULL DEFAULT 0,
    next_retry_at DATETIME NULL,
    lease_owner VARCHAR(128) NULL,
    lease_expires_at DATETIME NULL,
    context_json LONGTEXT NULL,
    failure_reason VARCHAR(1000) NULL,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    version INT NOT NULL DEFAULT 0,
    create_dept BIGINT NULL,
    create_by BIGINT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT NULL,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_ticket_task_call (tenant_id, policy_id, business_call_id),
    KEY idx_ai_ticket_task_dispatch (status, next_retry_at, lease_expires_at),
    KEY idx_ai_ticket_task_tenant (tenant_id, create_time)
) ENGINE=InnoDB COMMENT='AI ticket draft generation task';
