CREATE TABLE cc_ai_workflow_execution (
    id BIGINT NOT NULL,
    tenant_id VARCHAR(20) NOT NULL DEFAULT '000000',
    execution_id VARCHAR(64) NOT NULL,
    workflow_id BIGINT NOT NULL,
    workflow_version_id BIGINT NOT NULL,
    ai_agent_id BIGINT NULL,
    business_call_id VARCHAR(64) NULL,
    conversation_id BIGINT NULL,
    channel_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    current_node_id VARCHAR(64) NULL,
    context_json LONGTEXT NOT NULL,
    turn_no INT NOT NULL DEFAULT 0,
    total_node_count INT NOT NULL DEFAULT 0,
    last_input_id VARCHAR(128) NULL,
    started_at DATETIME NOT NULL,
    last_active_at DATETIME NOT NULL,
    ended_at DATETIME NULL,
    failure_code VARCHAR(64) NULL,
    failure_message VARCHAR(1000) NULL,
    lock_version INT NOT NULL DEFAULT 0,
    create_dept BIGINT NULL,
    create_by BIGINT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT NULL,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_workflow_execution (tenant_id, execution_id),
    KEY idx_ai_workflow_execution_version (tenant_id, workflow_version_id, status),
    KEY idx_ai_workflow_execution_call (tenant_id, business_call_id)
) ENGINE=InnoDB COMMENT='AI workflow execution';

CREATE TABLE cc_ai_workflow_node_log (
    id BIGINT NOT NULL,
    tenant_id VARCHAR(20) NOT NULL DEFAULT '000000',
    execution_id VARCHAR(64) NOT NULL,
    node_id VARCHAR(64) NOT NULL,
    node_type VARCHAR(64) NOT NULL,
    node_name VARCHAR(128) NULL,
    turn_no INT NOT NULL DEFAULT 0,
    attempt_no INT NOT NULL DEFAULT 1,
    input_summary VARCHAR(1000) NULL,
    output_summary VARCHAR(2000) NULL,
    execution_status VARCHAR(32) NOT NULL,
    branch_value VARCHAR(128) NULL,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(1000) NULL,
    started_at DATETIME NOT NULL,
    ended_at DATETIME NOT NULL,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    create_dept BIGINT NULL,
    create_by BIGINT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT NULL,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_ai_workflow_node_log_execution (tenant_id, execution_id, id),
    KEY idx_ai_workflow_node_log_node (tenant_id, node_type, execution_status)
) ENGINE=InnoDB COMMENT='AI workflow node execution log';

CREATE TABLE cc_ai_workflow_wait (
    id BIGINT NOT NULL,
    tenant_id VARCHAR(20) NOT NULL DEFAULT '000000',
    execution_id VARCHAR(64) NOT NULL,
    node_id VARCHAR(64) NOT NULL,
    wait_type VARCHAR(32) NOT NULL,
    wait_token VARCHAR(64) NOT NULL,
    expected_input_type VARCHAR(32) NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'WAITING',
    expires_at DATETIME NULL,
    resumed_at DATETIME NULL,
    create_dept BIGINT NULL,
    create_by BIGINT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT NULL,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_workflow_wait_token (tenant_id, wait_token),
    KEY idx_ai_workflow_wait_execution (tenant_id, execution_id, status)
) ENGINE=InnoDB COMMENT='AI workflow wait token';
