CREATE TABLE cc_outbound_attempt (
    id BIGINT NOT NULL COMMENT '外呼尝试ID',
    tenant_id VARCHAR(20) NOT NULL COMMENT '租户ID',
    task_id BIGINT NOT NULL COMMENT '外呼任务ID',
    member_id BIGINT NOT NULL COMMENT '外呼名单ID',
    customer_id BIGINT NOT NULL COMMENT '客户ID',
    agent_id BIGINT NULL COMMENT '执行坐席ID',
    user_id BIGINT NULL COMMENT '执行系统用户ID',
    attempt_no INT NOT NULL COMMENT '名单第几次拨打',
    business_call_id VARCHAR(64) NOT NULL COMMENT '业务通话标识',
    status VARCHAR(16) NOT NULL DEFAULT 'DIALING' COMMENT '尝试状态：DIALING拨打中、ANSWERED已接听、ENDED已结束',
    result_code VARCHAR(32) NULL COMMENT '坐席登记的外呼结果编码',
    result_remark VARCHAR(1000) NULL COMMENT '坐席登记的外呼结果备注',
    started_at DATETIME NOT NULL COMMENT '开始拨打时间',
    answered_at DATETIME NULL COMMENT '接听时间',
    ended_at DATETIME NULL COMMENT '结束时间',
    duration_seconds INT NOT NULL DEFAULT 0 COMMENT '总时长秒数',
    billable_seconds INT NOT NULL DEFAULT 0 COMMENT '接通时长秒数',
    hangup_cause VARCHAR(64) NULL COMMENT 'FreeSWITCH挂断原因',
    create_dept BIGINT NULL COMMENT '创建部门',
    create_by BIGINT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志',
    PRIMARY KEY (id),
    UNIQUE KEY uk_cc_outbound_attempt_call (tenant_id, business_call_id, deleted),
    KEY idx_cc_outbound_attempt_task (tenant_id, task_id, started_at),
    KEY idx_cc_outbound_attempt_member (tenant_id, member_id, attempt_no),
    KEY idx_cc_outbound_attempt_agent (tenant_id, agent_id, started_at)
) ENGINE=InnoDB COMMENT='外呼拨打尝试明细';
