ALTER TABLE cc_call_session
    ADD COLUMN owner_agent_id BIGINT NULL COMMENT '当前归属坐席ID' AFTER agent_extension,
    ADD COLUMN owner_agent_extension VARCHAR(32) NULL COMMENT '当前归属坐席分机' AFTER owner_agent_id,
    ADD COLUMN owner_agent_leg_uuid VARCHAR(64) NULL COMMENT '当前归属坐席通话腿UUID' AFTER owner_agent_extension,
    ADD COLUMN current_bridge_state VARCHAR(32) NULL COMMENT '当前桥接状态' AFTER owner_agent_leg_uuid,
    ADD KEY idx_cc_call_session_owner (tenant_id, owner_agent_id, call_status);

CREATE TABLE cc_call_leg (
    id                  BIGINT          NOT NULL COMMENT '通话腿ID',
    tenant_id           VARCHAR(20)     NOT NULL COMMENT '租户ID',
    session_id          BIGINT          NULL COMMENT '业务通话会话ID',
    business_call_id    VARCHAR(64)     NOT NULL COMMENT '业务通话ID',
    node_id             BIGINT          NOT NULL COMMENT 'FreeSWITCH节点ID',
    leg_uuid            VARCHAR(64)     NOT NULL COMMENT 'FreeSWITCH通话腿UUID',
    leg_role            VARCHAR(32)     NOT NULL DEFAULT 'UNKNOWN' COMMENT '通话腿角色：CUSTOMER客户、AGENT坐席、CONSULT_AGENT咨询坐席、SYSTEM系统、UNKNOWN未知',
    agent_id            BIGINT          NULL COMMENT '坐席ID',
    agent_extension     VARCHAR(32)     NULL COMMENT '坐席分机',
    caller_number       VARCHAR(64)     NULL COMMENT '主叫号码',
    called_number       VARCHAR(64)     NULL COMMENT '被叫号码',
    leg_state           VARCHAR(32)     NOT NULL DEFAULT 'CREATED' COMMENT '通话腿状态：CREATED创建、RINGING振铃、ANSWERED接听、BRIDGED桥接、HELD保持、PARKED驻留、ENDED结束',
    active              TINYINT         NOT NULL DEFAULT 1 COMMENT '是否仍在运行中',
    ringing_at          DATETIME        NULL COMMENT '振铃时间',
    answered_at         DATETIME        NULL COMMENT '接听时间',
    bridged_at          DATETIME        NULL COMMENT '桥接时间',
    held_at             DATETIME        NULL COMMENT '保持时间',
    parked_at           DATETIME        NULL COMMENT '驻留时间',
    ended_at            DATETIME        NULL COMMENT '结束时间',
    hangup_cause        VARCHAR(64)     NULL COMMENT '挂断原因',
    create_dept         BIGINT          NULL COMMENT '创建部门',
    create_by           BIGINT          NULL COMMENT '创建人',
    create_time         DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by           BIGINT          NULL COMMENT '更新人',
    update_time         DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version             INT             NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (id),
    UNIQUE KEY uk_cc_call_leg_uuid (tenant_id, leg_uuid),
    KEY idx_cc_call_leg_business (tenant_id, business_call_id, active),
    KEY idx_cc_call_leg_agent (tenant_id, agent_id, active),
    KEY idx_cc_call_leg_session (tenant_id, session_id)
) ENGINE=InnoDB COMMENT='通话腿状态表';

CREATE TABLE cc_call_bridge (
    id                  BIGINT          NOT NULL COMMENT '桥接关系ID',
    tenant_id           VARCHAR(20)     NOT NULL COMMENT '租户ID',
    session_id          BIGINT          NULL COMMENT '业务通话会话ID',
    business_call_id    VARCHAR(64)     NOT NULL COMMENT '业务通话ID',
    node_id             BIGINT          NOT NULL COMMENT 'FreeSWITCH节点ID',
    left_leg_uuid       VARCHAR(64)     NOT NULL COMMENT '左侧通话腿UUID',
    right_leg_uuid      VARCHAR(64)     NOT NULL COMMENT '右侧通话腿UUID',
    bridge_type         VARCHAR(32)     NOT NULL DEFAULT 'NORMAL' COMMENT '桥接类型：NORMAL普通、CONSULT咨询、TRANSFER转接、QUEUE队列',
    bridge_state        VARCHAR(32)     NOT NULL DEFAULT 'BRIDGED' COMMENT '桥接状态：BRIDGED已桥接、UNBRIDGED已拆桥',
    started_at          DATETIME        NOT NULL COMMENT '桥接开始时间',
    ended_at            DATETIME        NULL COMMENT '桥接结束时间',
    create_dept         BIGINT          NULL COMMENT '创建部门',
    create_by           BIGINT          NULL COMMENT '创建人',
    create_time         DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by           BIGINT          NULL COMMENT '更新人',
    update_time         DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version             INT             NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (id),
    KEY idx_cc_call_bridge_business (tenant_id, business_call_id, bridge_state),
    KEY idx_cc_call_bridge_left (tenant_id, left_leg_uuid, bridge_state),
    KEY idx_cc_call_bridge_right (tenant_id, right_leg_uuid, bridge_state)
) ENGINE=InnoDB COMMENT='通话桥接关系表';

CREATE TABLE cc_agent_call_session (
    id                  BIGINT          NOT NULL COMMENT '坐席通话会话ID',
    tenant_id           VARCHAR(20)     NOT NULL COMMENT '租户ID',
    session_id          BIGINT          NULL COMMENT '业务通话会话ID',
    business_call_id    VARCHAR(64)     NOT NULL COMMENT '业务通话ID',
    node_id             BIGINT          NOT NULL COMMENT 'FreeSWITCH节点ID',
    agent_id            BIGINT          NOT NULL COMMENT '坐席ID',
    agent_extension     VARCHAR(32)     NOT NULL COMMENT '坐席分机',
    agent_leg_uuid      VARCHAR(64)     NOT NULL COMMENT '坐席通话腿UUID',
    role                VARCHAR(32)     NOT NULL DEFAULT 'OWNER' COMMENT '坐席角色：OWNER当前归属、SOURCE转接发起方、CONSULT_TARGET咨询目标、MONITOR监听方',
    session_state       VARCHAR(32)     NOT NULL DEFAULT 'ACTIVE' COMMENT '会话状态：ACTIVE通话中、CONSULTING咨询中、TRANSFERRED已转接、ENDED已结束',
    visible             TINYINT         NOT NULL DEFAULT 1 COMMENT '前端是否展示为当前通话',
    joined_at           DATETIME        NOT NULL COMMENT '加入时间',
    left_at             DATETIME        NULL COMMENT '离开时间',
    create_dept         BIGINT          NULL COMMENT '创建部门',
    create_by           BIGINT          NULL COMMENT '创建人',
    create_time         DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by           BIGINT          NULL COMMENT '更新人',
    update_time         DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version             INT             NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (id),
    UNIQUE KEY uk_cc_agent_call_session_leg (tenant_id, agent_leg_uuid),
    KEY idx_cc_agent_call_session_agent (tenant_id, agent_id, session_state),
    KEY idx_cc_agent_call_session_business (tenant_id, business_call_id, visible)
) ENGINE=InnoDB COMMENT='坐席通话运行会话表';
