-- CallNexus 知识库、FAQ、AI 助手与 RAG 会话。
-- MySQL 保存业务事实，原始文件保存到 OSS，向量保存到 Qdrant。

CREATE TABLE IF NOT EXISTS cc_ai_model_provider (
    id BIGINT NOT NULL COMMENT '模型服务商ID',
    tenant_id VARCHAR(20) NOT NULL COMMENT '租户ID',
    provider_code VARCHAR(64) NOT NULL COMMENT '服务商编码',
    provider_name VARCHAR(128) NOT NULL COMMENT '服务商名称',
    provider_type VARCHAR(32) NOT NULL COMMENT '服务商类型：OPENAI_COMPATIBLE',
    base_url VARCHAR(512) NOT NULL COMMENT 'OpenAI兼容接口基础地址',
    api_key VARCHAR(2048) NULL COMMENT '加密保存的API密钥',
    organization_id VARCHAR(128) NULL COMMENT '组织ID',
    connect_timeout_seconds INT NOT NULL DEFAULT 10 COMMENT '连接超时秒数',
    read_timeout_seconds INT NOT NULL DEFAULT 120 COMMENT '读取超时秒数',
    extra_config_json TEXT NULL COMMENT '服务商扩展配置JSON',
    enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
    create_dept BIGINT NULL COMMENT '创建部门',
    create_by BIGINT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志',
    PRIMARY KEY (id),
    UNIQUE KEY uk_cc_ai_model_provider_code (tenant_id, provider_code, deleted),
    KEY idx_cc_ai_model_provider_enabled (tenant_id, enabled)
) ENGINE=InnoDB COMMENT='AI模型服务商配置表';

CREATE TABLE IF NOT EXISTS cc_ai_model (
    id BIGINT NOT NULL COMMENT 'AI模型ID',
    tenant_id VARCHAR(20) NOT NULL COMMENT '租户ID',
    provider_id BIGINT NOT NULL COMMENT '模型服务商ID',
    model_code VARCHAR(64) NOT NULL COMMENT '模型业务编码',
    model_name VARCHAR(128) NOT NULL COMMENT '接口实际模型名称',
    capability VARCHAR(32) NOT NULL COMMENT '模型能力：CHAT、EMBEDDING、RERANK',
    vector_dimension INT NULL COMMENT '向量维度',
    max_batch_size INT NOT NULL DEFAULT 16 COMMENT '单次向量化最大批量',
    max_input_tokens INT NULL COMMENT '最大输入Token数',
    default_model TINYINT NOT NULL DEFAULT 0 COMMENT '是否为能力默认模型',
    request_options_json TEXT NULL COMMENT '请求扩展参数JSON',
    enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
    create_dept BIGINT NULL COMMENT '创建部门',
    create_by BIGINT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志',
    PRIMARY KEY (id),
    UNIQUE KEY uk_cc_ai_model_code (tenant_id, model_code, deleted),
    KEY idx_cc_ai_model_provider (tenant_id, provider_id, capability, enabled)
) ENGINE=InnoDB COMMENT='AI模型配置表';

CREATE TABLE IF NOT EXISTS cc_ai_knowledge_base (
    id BIGINT NOT NULL COMMENT '知识库ID',
    tenant_id VARCHAR(20) NOT NULL COMMENT '租户ID',
    knowledge_code VARCHAR(64) NOT NULL COMMENT '知识库编码',
    knowledge_name VARCHAR(128) NOT NULL COMMENT '知识库名称',
    description VARCHAR(1000) NULL COMMENT '知识库说明',
    embedding_model_id BIGINT NOT NULL COMMENT '向量模型ID',
    collection_name VARCHAR(128) NULL COMMENT 'Qdrant集合名称',
    pending_embedding_model_id BIGINT NULL COMMENT '重建完成后待切换的向量模型ID',
    pending_collection_name VARCHAR(128) NULL COMMENT '重建完成后待切换的Qdrant集合名称',
    rebuild_batch_id VARCHAR(64) NULL COMMENT '当前索引重建批次ID',
    chunk_size INT NOT NULL DEFAULT 800 COMMENT '切片字符数',
    chunk_overlap INT NOT NULL DEFAULT 100 COMMENT '切片重叠字符数',
    default_top_k INT NOT NULL DEFAULT 5 COMMENT '默认文档检索数量',
    score_threshold DECIMAL(10,8) NOT NULL DEFAULT 0.50000000 COMMENT '文档检索阈值',
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '状态：DRAFT、INDEXING、READY、PARTIAL、FAILED、DISABLED',
    document_count INT NOT NULL DEFAULT 0 COMMENT '文档数量',
    faq_count INT NOT NULL DEFAULT 0 COMMENT 'FAQ数量',
    chunk_count INT NOT NULL DEFAULT 0 COMMENT '有效切片数量',
    last_indexed_at DATETIME NULL COMMENT '最近索引完成时间',
    failure_reason VARCHAR(1000) NULL COMMENT '最近失败原因',
    enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
    create_dept BIGINT NULL COMMENT '创建部门',
    create_by BIGINT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志',
    PRIMARY KEY (id),
    UNIQUE KEY uk_cc_ai_knowledge_code (tenant_id, knowledge_code, deleted),
    KEY idx_cc_ai_knowledge_model (tenant_id, embedding_model_id, enabled)
) ENGINE=InnoDB COMMENT='AI知识库表';

CREATE TABLE IF NOT EXISTS cc_ai_knowledge_document (
    id BIGINT NOT NULL COMMENT '知识文档ID',
    tenant_id VARCHAR(20) NOT NULL COMMENT '租户ID',
    knowledge_base_id BIGINT NOT NULL COMMENT '知识库ID',
    document_name VARCHAR(255) NOT NULL COMMENT '文档名称',
    document_type VARCHAR(32) NOT NULL COMMENT '文档类型',
    current_version_id BIGINT NULL COMMENT '当前生效版本ID',
    status VARCHAR(32) NOT NULL DEFAULT 'UPLOADED' COMMENT '状态：UPLOADED、PROCESSING、READY、FAILED、DISABLED',
    enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
    create_dept BIGINT NULL COMMENT '创建部门',
    create_by BIGINT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志',
    PRIMARY KEY (id),
    KEY idx_cc_ai_document_kb (tenant_id, knowledge_base_id, status)
) ENGINE=InnoDB COMMENT='AI知识文档表';

CREATE TABLE IF NOT EXISTS cc_ai_knowledge_document_version (
    id BIGINT NOT NULL COMMENT '知识文档版本ID',
    tenant_id VARCHAR(20) NOT NULL COMMENT '租户ID',
    knowledge_base_id BIGINT NOT NULL COMMENT '知识库ID',
    document_id BIGINT NOT NULL COMMENT '知识文档ID',
    version_no INT NOT NULL COMMENT '版本号',
    oss_id BIGINT NOT NULL COMMENT '原始文件OSS ID',
    original_file_name VARCHAR(255) NOT NULL COMMENT '原始文件名',
    content_type VARCHAR(128) NULL COMMENT '内容类型',
    file_size BIGINT NOT NULL COMMENT '文件大小',
    checksum VARCHAR(128) NOT NULL COMMENT '文件SHA256',
    parse_status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '解析状态',
    index_status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '索引状态',
    page_count INT NULL COMMENT '页数或Sheet数',
    character_count INT NULL COMMENT '提取字符数',
    chunk_count INT NULL COMMENT '切片数量',
    failure_reason VARCHAR(1000) NULL COMMENT '失败原因',
    started_at DATETIME NULL COMMENT '开始时间',
    finished_at DATETIME NULL COMMENT '完成时间',
    create_dept BIGINT NULL COMMENT '创建部门',
    create_by BIGINT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志',
    PRIMARY KEY (id),
    UNIQUE KEY uk_cc_ai_document_version (tenant_id, document_id, version_no, deleted),
    KEY idx_cc_ai_document_version_status (tenant_id, knowledge_base_id, index_status)
) ENGINE=InnoDB COMMENT='AI知识文档版本表';

CREATE TABLE IF NOT EXISTS cc_ai_knowledge_chunk (
    id BIGINT NOT NULL COMMENT '知识切片ID',
    tenant_id VARCHAR(20) NOT NULL COMMENT '租户ID',
    knowledge_base_id BIGINT NOT NULL COMMENT '知识库ID',
    document_id BIGINT NOT NULL COMMENT '文档ID',
    document_version_id BIGINT NOT NULL COMMENT '文档版本ID',
    chunk_index INT NOT NULL COMMENT '切片序号',
    title_path VARCHAR(500) NULL COMMENT '标题路径',
    page_number INT NULL COMMENT '页码',
    sheet_name VARCHAR(128) NULL COMMENT 'Sheet名称',
    row_start INT NULL COMMENT '起始行',
    row_end INT NULL COMMENT '结束行',
    text_content MEDIUMTEXT NOT NULL COMMENT '切片正文',
    text_hash VARCHAR(128) NOT NULL COMMENT '正文哈希',
    token_estimate INT NULL COMMENT 'Token估算数',
    qdrant_point_id VARCHAR(64) NOT NULL COMMENT 'Qdrant Point ID',
    index_state VARCHAR(32) NOT NULL DEFAULT 'STAGING' COMMENT '索引状态：STAGING、ACTIVE、RETIRED、FAILED',
    create_dept BIGINT NULL COMMENT '创建部门',
    create_by BIGINT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志',
    PRIMARY KEY (id),
    UNIQUE KEY uk_cc_ai_chunk_index (tenant_id, document_version_id, chunk_index, deleted),
    KEY idx_cc_ai_chunk_active (tenant_id, knowledge_base_id, index_state),
    KEY idx_cc_ai_chunk_document (tenant_id, document_id, document_version_id)
) ENGINE=InnoDB COMMENT='AI知识切片表';

CREATE TABLE IF NOT EXISTS cc_ai_knowledge_faq (
    id BIGINT NOT NULL COMMENT 'FAQ ID',
    tenant_id VARCHAR(20) NOT NULL COMMENT '租户ID',
    knowledge_base_id BIGINT NOT NULL COMMENT '知识库ID',
    faq_code VARCHAR(64) NOT NULL COMMENT 'FAQ编码',
    faq_name VARCHAR(128) NOT NULL COMMENT 'FAQ名称',
    current_version_id BIGINT NULL COMMENT '当前生效版本ID',
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '状态：DRAFT、INDEXING、READY、FAILED、DISABLED',
    answer_mode VARCHAR(32) NOT NULL DEFAULT 'DIRECT' COMMENT '回答模式：DIRECT、CONTEXT',
    enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
    create_dept BIGINT NULL COMMENT '创建部门',
    create_by BIGINT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志',
    PRIMARY KEY (id),
    UNIQUE KEY uk_cc_ai_faq_code (tenant_id, knowledge_base_id, faq_code, deleted),
    KEY idx_cc_ai_faq_ready (tenant_id, knowledge_base_id, enabled, status)
) ENGINE=InnoDB COMMENT='AI知识库FAQ表';

CREATE TABLE IF NOT EXISTS cc_ai_knowledge_faq_version (
    id BIGINT NOT NULL COMMENT 'FAQ版本ID',
    tenant_id VARCHAR(20) NOT NULL COMMENT '租户ID',
    knowledge_base_id BIGINT NOT NULL COMMENT '知识库ID',
    faq_id BIGINT NOT NULL COMMENT 'FAQ ID',
    version_no INT NOT NULL COMMENT '版本号',
    standard_question VARCHAR(1000) NOT NULL COMMENT '标准问题',
    normalized_question VARCHAR(1000) NOT NULL COMMENT '规范化问题',
    standard_answer MEDIUMTEXT NOT NULL COMMENT '标准答案',
    question_hash VARCHAR(128) NOT NULL COMMENT '问题哈希',
    answer_hash VARCHAR(128) NOT NULL COMMENT '答案哈希',
    primary_qdrant_point_id VARCHAR(64) NULL COMMENT '标准问题向量点ID',
    index_status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '索引状态',
    failure_reason VARCHAR(1000) NULL COMMENT '失败原因',
    started_at DATETIME NULL COMMENT '开始时间',
    finished_at DATETIME NULL COMMENT '完成时间',
    create_dept BIGINT NULL COMMENT '创建部门',
    create_by BIGINT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志',
    PRIMARY KEY (id),
    UNIQUE KEY uk_cc_ai_faq_version (tenant_id, faq_id, version_no, deleted),
    KEY idx_cc_ai_faq_question (tenant_id, knowledge_base_id, normalized_question(191))
) ENGINE=InnoDB COMMENT='AI知识库FAQ版本表';

CREATE TABLE IF NOT EXISTS cc_ai_knowledge_faq_alias (
    id BIGINT NOT NULL COMMENT 'FAQ相似问法ID',
    tenant_id VARCHAR(20) NOT NULL COMMENT '租户ID',
    knowledge_base_id BIGINT NOT NULL COMMENT '知识库ID',
    faq_id BIGINT NOT NULL COMMENT 'FAQ ID',
    faq_version_id BIGINT NOT NULL COMMENT 'FAQ版本ID',
    alias_question VARCHAR(1000) NOT NULL COMMENT '相似问法',
    normalized_question VARCHAR(1000) NOT NULL COMMENT '规范化问法',
    question_hash VARCHAR(128) NOT NULL COMMENT '问法哈希',
    qdrant_point_id VARCHAR(64) NOT NULL COMMENT 'Qdrant Point ID',
    index_state VARCHAR(32) NOT NULL DEFAULT 'STAGING' COMMENT '索引状态',
    create_dept BIGINT NULL COMMENT '创建部门',
    create_by BIGINT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志',
    PRIMARY KEY (id),
    UNIQUE KEY uk_cc_ai_faq_alias_hash (tenant_id, knowledge_base_id, question_hash, deleted),
    KEY idx_cc_ai_faq_alias_version (tenant_id, faq_version_id, index_state)
) ENGINE=InnoDB COMMENT='AI知识库FAQ相似问法表';

CREATE TABLE IF NOT EXISTS cc_ai_knowledge_task (
    id BIGINT NOT NULL COMMENT '知识处理任务ID',
    tenant_id VARCHAR(20) NOT NULL COMMENT '租户ID',
    task_type VARCHAR(32) NOT NULL COMMENT '任务类型：PARSE_AND_INDEX、FAQ_INDEX、REINDEX、DELETE_INDEX、DELETE_FAQ_INDEX',
    knowledge_base_id BIGINT NOT NULL COMMENT '知识库ID',
    document_id BIGINT NULL COMMENT '文档ID',
    document_version_id BIGINT NULL COMMENT '文档版本ID',
    faq_id BIGINT NULL COMMENT 'FAQ ID',
    faq_version_id BIGINT NULL COMMENT 'FAQ版本ID',
    target_embedding_model_id BIGINT NULL COMMENT '本任务使用的目标向量模型ID',
    target_collection_name VARCHAR(128) NULL COMMENT '本任务写入的目标Qdrant集合名称',
    rebuild_batch_id VARCHAR(64) NULL COMMENT '索引重建批次ID',
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '状态：PENDING、PROCESSING、SUCCESS、FAILED',
    retry_count INT NOT NULL DEFAULT 0 COMMENT '重试次数',
    next_retry_at DATETIME NULL COMMENT '下次重试时间',
    lease_owner VARCHAR(128) NULL COMMENT '租约持有者',
    lease_expires_at DATETIME NULL COMMENT '租约到期时间',
    progress_total INT NOT NULL DEFAULT 0 COMMENT '总进度数',
    progress_completed INT NOT NULL DEFAULT 0 COMMENT '已完成数',
    failure_reason VARCHAR(1000) NULL COMMENT '失败原因',
    started_at DATETIME NULL COMMENT '开始时间',
    finished_at DATETIME NULL COMMENT '完成时间',
    create_dept BIGINT NULL COMMENT '创建部门',
    create_by BIGINT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志',
    PRIMARY KEY (id),
    KEY idx_cc_ai_task_claim (status, next_retry_at, lease_expires_at, create_time),
    KEY idx_cc_ai_task_business (tenant_id, knowledge_base_id, document_id, faq_id),
    KEY idx_cc_ai_task_rebuild (tenant_id, rebuild_batch_id, status)
) ENGINE=InnoDB COMMENT='AI知识处理任务表';

CREATE TABLE IF NOT EXISTS cc_ai_agent (
    id BIGINT NOT NULL COMMENT 'AI助手ID',
    tenant_id VARCHAR(20) NOT NULL COMMENT '租户ID',
    agent_code VARCHAR(64) NOT NULL COMMENT '助手编码',
    agent_name VARCHAR(128) NOT NULL COMMENT '助手名称',
    description VARCHAR(1000) NULL COMMENT '助手说明',
    chat_model_id BIGINT NOT NULL COMMENT '对话模型ID',
    system_prompt TEXT NULL COMMENT '系统提示词',
    retrieval_mode VARCHAR(32) NOT NULL DEFAULT 'STRICT' COMMENT '检索模式：STRICT、FALLBACK_MODEL',
    retrieval_failure_policy VARCHAR(32) NOT NULL DEFAULT 'FAIL_CLOSED' COMMENT '检索故障策略',
    top_k INT NOT NULL DEFAULT 5 COMMENT '文档检索数量',
    score_threshold DECIMAL(10,8) NOT NULL DEFAULT 0.50000000 COMMENT '文档检索阈值',
    faq_score_threshold DECIMAL(10,8) NOT NULL DEFAULT 0.80000000 COMMENT 'FAQ语义阈值',
    temperature DECIMAL(6,4) NOT NULL DEFAULT 0.2000 COMMENT '模型温度',
    max_output_tokens INT NOT NULL DEFAULT 1024 COMMENT '最大输出Token',
    history_message_limit INT NOT NULL DEFAULT 10 COMMENT '携带历史消息数',
    enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
    create_dept BIGINT NULL COMMENT '创建部门',
    create_by BIGINT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志',
    PRIMARY KEY (id),
    UNIQUE KEY uk_cc_ai_agent_code (tenant_id, agent_code, deleted),
    KEY idx_cc_ai_agent_enabled (tenant_id, enabled)
) ENGINE=InnoDB COMMENT='AI助手表';

CREATE TABLE IF NOT EXISTS cc_ai_agent_knowledge_base (
    id BIGINT NOT NULL COMMENT '助手知识库绑定ID',
    tenant_id VARCHAR(20) NOT NULL COMMENT '租户ID',
    agent_id BIGINT NOT NULL COMMENT 'AI助手ID',
    knowledge_base_id BIGINT NOT NULL COMMENT '知识库ID',
    priority INT NOT NULL DEFAULT 1 COMMENT '优先级，越小越优先',
    enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
    create_dept BIGINT NULL COMMENT '创建部门',
    create_by BIGINT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志',
    PRIMARY KEY (id),
    UNIQUE KEY uk_cc_ai_agent_kb (tenant_id, agent_id, knowledge_base_id, deleted),
    UNIQUE KEY uk_cc_ai_agent_priority (tenant_id, agent_id, priority, deleted)
) ENGINE=InnoDB COMMENT='AI助手知识库绑定表';

CREATE TABLE IF NOT EXISTS cc_ai_conversation (
    id BIGINT NOT NULL COMMENT 'AI会话ID',
    tenant_id VARCHAR(20) NOT NULL COMMENT '租户ID',
    agent_id BIGINT NOT NULL COMMENT 'AI助手ID',
    user_id BIGINT NOT NULL COMMENT '系统用户ID',
    title VARCHAR(255) NOT NULL COMMENT '会话标题',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE、ARCHIVED',
    last_message_at DATETIME NULL COMMENT '最后消息时间',
    create_dept BIGINT NULL COMMENT '创建部门',
    create_by BIGINT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志',
    PRIMARY KEY (id),
    KEY idx_cc_ai_conversation_user (tenant_id, user_id, last_message_at),
    KEY idx_cc_ai_conversation_agent (tenant_id, agent_id)
) ENGINE=InnoDB COMMENT='AI助手会话表';

CREATE TABLE IF NOT EXISTS cc_ai_message (
    id BIGINT NOT NULL COMMENT 'AI消息ID',
    tenant_id VARCHAR(20) NOT NULL COMMENT '租户ID',
    conversation_id BIGINT NOT NULL COMMENT '会话ID',
    agent_id BIGINT NOT NULL COMMENT 'AI助手ID',
    role VARCHAR(32) NOT NULL COMMENT '角色：USER、ASSISTANT、SYSTEM',
    content MEDIUMTEXT NOT NULL COMMENT '消息内容',
    source_type VARCHAR(32) NULL COMMENT '回答来源：FAQ、DOCUMENT、MODEL_FALLBACK、STRICT_REJECT',
    status VARCHAR(32) NOT NULL DEFAULT 'SUCCESS' COMMENT '状态：PROCESSING、SUCCESS、FAILED、INTERRUPTED',
    request_id VARCHAR(64) NULL COMMENT '请求追踪ID',
    failure_reason VARCHAR(1000) NULL COMMENT '失败原因',
    create_dept BIGINT NULL COMMENT '创建部门',
    create_by BIGINT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志',
    PRIMARY KEY (id),
    KEY idx_cc_ai_message_conversation (tenant_id, conversation_id, create_time)
) ENGINE=InnoDB COMMENT='AI助手消息表';

CREATE TABLE IF NOT EXISTS cc_ai_message_citation (
    id BIGINT NOT NULL COMMENT 'AI消息引用ID',
    tenant_id VARCHAR(20) NOT NULL COMMENT '租户ID',
    message_id BIGINT NOT NULL COMMENT '助手消息ID',
    source_type VARCHAR(32) NOT NULL COMMENT '来源类型：FAQ、DOCUMENT',
    knowledge_base_id BIGINT NOT NULL COMMENT '知识库ID',
    document_id BIGINT NULL COMMENT '文档ID',
    document_version_id BIGINT NULL COMMENT '文档版本ID',
    chunk_id BIGINT NULL COMMENT '切片ID',
    faq_id BIGINT NULL COMMENT 'FAQ ID',
    faq_version_id BIGINT NULL COMMENT 'FAQ版本ID',
    source_name VARCHAR(255) NULL COMMENT '来源名称',
    source_location VARCHAR(500) NULL COMMENT '页码、Sheet或标准问题',
    quoted_content TEXT NULL COMMENT '引用内容快照',
    score DECIMAL(10,8) NULL COMMENT '相似度',
    create_dept BIGINT NULL COMMENT '创建部门',
    create_by BIGINT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志',
    PRIMARY KEY (id),
    KEY idx_cc_ai_citation_message (tenant_id, message_id)
) ENGINE=InnoDB COMMENT='AI助手消息引用表';

CREATE TABLE IF NOT EXISTS cc_ai_model_usage (
    id BIGINT NOT NULL COMMENT '模型调用记录ID',
    tenant_id VARCHAR(20) NOT NULL COMMENT '租户ID',
    conversation_id BIGINT NULL COMMENT '会话ID',
    message_id BIGINT NULL COMMENT '消息ID',
    provider_id BIGINT NOT NULL COMMENT '服务商ID',
    model_id BIGINT NOT NULL COMMENT '模型ID',
    capability VARCHAR(32) NOT NULL COMMENT '调用能力',
    request_id VARCHAR(64) NOT NULL COMMENT '请求追踪ID',
    input_tokens INT NULL COMMENT '输入Token数',
    output_tokens INT NULL COMMENT '输出Token数',
    elapsed_ms BIGINT NOT NULL COMMENT '调用耗时毫秒',
    status VARCHAR(32) NOT NULL COMMENT '状态：SUCCESS、FAILED',
    error_code VARCHAR(128) NULL COMMENT '错误码',
    error_message VARCHAR(1000) NULL COMMENT '脱敏错误信息',
    create_dept BIGINT NULL COMMENT '创建部门',
    create_by BIGINT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志',
    PRIMARY KEY (id),
    KEY idx_cc_ai_usage_request (tenant_id, request_id),
    KEY idx_cc_ai_usage_model (tenant_id, model_id, create_time)
) ENGINE=InnoDB COMMENT='AI模型调用审计表';
