-- AI 实时语音会话与轮次。业务通话、FreeSWITCH 电话腿和 AI 会话分别保存，禁止混用 UUID。
CREATE TABLE IF NOT EXISTS cc_ai_realtime_call_session (
    id BIGINT NOT NULL COMMENT 'AI实时语音会话ID',
    tenant_id VARCHAR(20) NOT NULL COMMENT '租户ID',
    business_call_id VARCHAR(64) NOT NULL COMMENT '业务通话ID',
    customer_leg_uuid VARCHAR(64) NOT NULL COMMENT '客户电话腿UUID',
    node_id BIGINT NOT NULL COMMENT 'FreeSWITCH节点ID',
    flow_id BIGINT NOT NULL COMMENT 'IVR流程ID',
    ai_agent_id BIGINT NOT NULL COMMENT 'AI助手ID',
    conversation_id BIGINT NULL COMMENT 'AI文本会话ID',
    asr_provider_id BIGINT NOT NULL COMMENT '流式ASR服务商ID',
    tts_provider_id BIGINT NOT NULL COMMENT 'TTS服务商ID',
    session_state VARCHAR(32) NOT NULL COMMENT '状态：CONNECTING、LISTENING、THINKING、SPEAKING、ENDED、FAILED',
    connected_at DATETIME NOT NULL COMMENT '音频连接时间',
    last_activity_at DATETIME NOT NULL COMMENT '最近活动时间',
    ended_at DATETIME NULL COMMENT '结束时间',
    failure_reason VARCHAR(1000) NULL COMMENT '失败原因',
    create_dept BIGINT NULL COMMENT '创建部门',
    create_by BIGINT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (id),
    KEY idx_cc_ai_realtime_business_call (tenant_id, business_call_id),
    KEY idx_cc_ai_realtime_customer_leg (tenant_id, customer_leg_uuid),
    KEY idx_cc_ai_realtime_state (tenant_id, session_state, last_activity_at)
) ENGINE=InnoDB COMMENT='AI实时语音会话表';

CREATE TABLE IF NOT EXISTS cc_ai_realtime_call_turn (
    id BIGINT NOT NULL COMMENT 'AI实时语音轮次ID',
    tenant_id VARCHAR(20) NOT NULL COMMENT '租户ID',
    realtime_session_id BIGINT NOT NULL COMMENT 'AI实时语音会话ID',
    sequence_no INT NOT NULL COMMENT '轮次序号',
    user_text TEXT NOT NULL COMMENT '客户识别文本',
    assistant_text MEDIUMTEXT NULL COMMENT 'AI回答文本',
    answer_source VARCHAR(32) NULL COMMENT '回答来源：FAQ、DOCUMENT、MODEL等',
    turn_state VARCHAR(32) NOT NULL COMMENT '状态：THINKING、SPEAKING、COMPLETED、FAILED',
    recognized_at DATETIME NOT NULL COMMENT '识别完成时间',
    answered_at DATETIME NULL COMMENT '回答生成时间',
    playback_started_at DATETIME NULL COMMENT '播放开始时间',
    playback_ended_at DATETIME NULL COMMENT '播放结束时间',
    failure_reason VARCHAR(1000) NULL COMMENT '失败原因',
    create_dept BIGINT NULL COMMENT '创建部门',
    create_by BIGINT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_cc_ai_realtime_turn (tenant_id, realtime_session_id, sequence_no),
    KEY idx_cc_ai_realtime_turn_state (tenant_id, turn_state, create_time)
) ENGINE=InnoDB COMMENT='AI实时语音轮次表';
