-- 普通通话升级多方会议。业务通话、电话腿 UUID 与 FreeSWITCH 会议成员 ID 分开保存。
CREATE TABLE IF NOT EXISTS cc_call_conference (
    id BIGINT NOT NULL COMMENT '会议ID',
    tenant_id VARCHAR(20) NOT NULL COMMENT '租户ID',
    session_id BIGINT NOT NULL COMMENT '业务通话会话ID',
    business_call_id VARCHAR(64) NOT NULL COMMENT '业务通话ID',
    node_id BIGINT NOT NULL COMMENT 'FreeSWITCH节点ID',
    conference_name VARCHAR(128) NOT NULL COMMENT 'FreeSWITCH会议房间名',
    owner_agent_id BIGINT NOT NULL COMMENT '发起坐席ID',
    owner_extension VARCHAR(64) NOT NULL COMMENT '发起坐席分机',
    conference_state VARCHAR(32) NOT NULL COMMENT '状态：CREATING、ACTIVE、ENDED、FAILED',
    started_at DATETIME NULL COMMENT '会议开始时间',
    ended_at DATETIME NULL COMMENT '会议结束时间',
    failure_reason VARCHAR(1000) NULL COMMENT '失败原因',
    create_dept BIGINT NULL COMMENT '创建部门',
    create_by BIGINT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志',
    PRIMARY KEY (id),
    UNIQUE KEY uk_cc_call_conference_active (tenant_id, business_call_id, deleted),
    KEY idx_cc_call_conference_session (tenant_id, session_id, conference_state),
    KEY idx_cc_call_conference_room (tenant_id, node_id, conference_name)
) ENGINE=InnoDB COMMENT='通话多方会议表';

CREATE TABLE IF NOT EXISTS cc_call_conference_member (
    id BIGINT NOT NULL COMMENT '会议成员记录ID',
    tenant_id VARCHAR(20) NOT NULL COMMENT '租户ID',
    conference_id BIGINT NOT NULL COMMENT '会议ID',
    session_id BIGINT NOT NULL COMMENT '业务通话会话ID',
    business_call_id VARCHAR(64) NOT NULL COMMENT '业务通话ID',
    leg_uuid VARCHAR(64) NOT NULL COMMENT '电话腿UUID',
    conference_member_id VARCHAR(32) NULL COMMENT 'FreeSWITCH会议成员ID',
    member_role VARCHAR(32) NOT NULL COMMENT '角色：CUSTOMER、OWNER_AGENT、INVITED_EXTENSION',
    agent_id BIGINT NULL COMMENT '坐席ID',
    extension VARCHAR(64) NULL COMMENT '成员分机',
    display_name VARCHAR(128) NULL COMMENT '显示名称',
    member_state VARCHAR(32) NOT NULL COMMENT '状态：INVITING、JOINED、LEFT、FAILED',
    muted TINYINT NOT NULL DEFAULT 0 COMMENT '是否被会议静音',
    invited_at DATETIME NULL COMMENT '邀请时间',
    joined_at DATETIME NULL COMMENT '加入时间',
    left_at DATETIME NULL COMMENT '离开时间',
    failure_reason VARCHAR(1000) NULL COMMENT '失败原因',
    create_dept BIGINT NULL COMMENT '创建部门',
    create_by BIGINT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志',
    PRIMARY KEY (id),
    UNIQUE KEY uk_cc_call_conference_member_leg (tenant_id, conference_id, leg_uuid, deleted),
    KEY idx_cc_call_conference_member_state (tenant_id, conference_id, member_state),
    KEY idx_cc_call_conference_member_extension (tenant_id, extension, member_state)
) ENGINE=InnoDB COMMENT='通话多方会议成员表';
