-- 客户批量导入批次、行明细与客户归属。

CREATE TABLE IF NOT EXISTS cc_customer_import_batch (
    id BIGINT NOT NULL COMMENT '导入批次ID',
    tenant_id VARCHAR(20) NOT NULL COMMENT '租户ID',
    file_name VARCHAR(255) NULL COMMENT '导入文件名',
    status VARCHAR(32) NOT NULL COMMENT '状态：PENDING、IMPORTING、PROCESSING、SUCCESS、PARTIAL_SUCCESS、FAILED',
    duplicate_strategy VARCHAR(32) NOT NULL COMMENT '重复处理：SKIP、UPDATE_ASSIGNMENT',
    default_customer_type VARCHAR(64) NULL COMMENT '默认客户类型',
    default_source_channel VARCHAR(64) NULL COMMENT '默认来源渠道',
    default_tags VARCHAR(255) NULL COMMENT '默认客户标签',
    default_skill_group_id BIGINT NULL COMMENT '默认分配技能组ID',
    default_agent_id BIGINT NULL COMMENT '默认分配坐席ID',
    default_remark VARCHAR(500) NULL COMMENT '默认备注',
    total_count INT NOT NULL DEFAULT 0 COMMENT '总行数',
    imported_count INT NOT NULL DEFAULT 0 COMMENT '导入成功数',
    skipped_count INT NOT NULL DEFAULT 0 COMMENT '跳过数',
    failed_count INT NOT NULL DEFAULT 0 COMMENT '失败数',
    failure_reason VARCHAR(1000) NULL COMMENT '失败原因',
    create_dept BIGINT NULL COMMENT '创建部门',
    create_by BIGINT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志',
    PRIMARY KEY (id),
    KEY idx_cc_customer_import_batch_status (tenant_id, status, create_time)
) ENGINE=InnoDB COMMENT='客户导入批次表';

CREATE TABLE IF NOT EXISTS cc_customer_import_row (
    id BIGINT NOT NULL COMMENT '导入行ID',
    tenant_id VARCHAR(20) NOT NULL COMMENT '租户ID',
    batch_id BIGINT NOT NULL COMMENT '导入批次ID',
    source_row_number INT NOT NULL COMMENT 'Excel源行号',
    customer_name VARCHAR(128) NULL COMMENT '客户姓名',
    original_phone VARCHAR(64) NULL COMMENT '原始主号码',
    normalized_phone VARCHAR(64) NULL COMMENT '清洗后主号码',
    additional_phones VARCHAR(1000) NULL COMMENT '附加号码原文',
    customer_type VARCHAR(64) NULL COMMENT '客户类型',
    source_channel VARCHAR(64) NULL COMMENT '来源渠道',
    tags VARCHAR(255) NULL COMMENT '客户标签',
    skill_group_id BIGINT NULL COMMENT '分配技能组ID',
    agent_id BIGINT NULL COMMENT '分配坐席ID',
    status VARCHAR(32) NOT NULL COMMENT '状态：IMPORTED、SKIPPED、FAILED',
    error_message VARCHAR(1000) NULL COMMENT '提示或失败原因',
    customer_id BIGINT NULL COMMENT '关联客户ID',
    raw_json TEXT NULL COMMENT '原始行JSON',
    create_dept BIGINT NULL COMMENT '创建部门',
    create_by BIGINT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志',
    PRIMARY KEY (id),
    KEY idx_cc_customer_import_row_batch (tenant_id, batch_id, source_row_number),
    KEY idx_cc_customer_import_row_status (tenant_id, batch_id, status),
    KEY idx_cc_customer_import_row_customer (tenant_id, customer_id)
) ENGINE=InnoDB COMMENT='客户导入行明细表';

CREATE TABLE IF NOT EXISTS cc_customer_assignment (
    id BIGINT NOT NULL COMMENT '客户归属ID',
    tenant_id VARCHAR(20) NOT NULL COMMENT '租户ID',
    customer_id BIGINT NOT NULL COMMENT '客户ID',
    customer_type VARCHAR(64) NULL COMMENT '客户类型',
    source_channel VARCHAR(64) NULL COMMENT '来源渠道',
    tags VARCHAR(255) NULL COMMENT '客户标签',
    skill_group_id BIGINT NULL COMMENT '归属技能组ID',
    agent_id BIGINT NULL COMMENT '归属坐席ID',
    assignment_source VARCHAR(32) NOT NULL COMMENT '归属来源：IMPORT_CREATE、IMPORT_UPDATE、MANUAL',
    import_batch_id BIGINT NULL COMMENT '导入批次ID',
    remark VARCHAR(500) NULL COMMENT '备注',
    enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否当前生效',
    create_dept BIGINT NULL COMMENT '创建部门',
    create_by BIGINT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志',
    PRIMARY KEY (id),
    KEY idx_cc_customer_assignment_customer (tenant_id, customer_id, enabled),
    KEY idx_cc_customer_assignment_group (tenant_id, skill_group_id, enabled),
    KEY idx_cc_customer_assignment_agent (tenant_id, agent_id, enabled)
) ENGINE=InnoDB COMMENT='客户归属表';
